<?php
/*
 * Turiknox_Hotjar

 * @category   Turiknox
 * @package    Turiknox_Hotjar
 * @copyright  Copyright (c) 2017 Turiknox
 * @license    https://github.com/Turiknox/magento2-hotjar/blob/master/LICENSE.md
 * @version    1.0.0
 */
?>
<?php if ($block->isEnabled()): ?>
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:<?php echo $block->escapeHtml($block->getHjSiteId()); ?>,hjsv:5};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<?php endif; ?>
